### ISSUE TITLE
Changing of namespace not allowed

### ISSUE THREAD

**Issue by amezioud** [anapsix/k8s-vault.cr#1]
First, thank you very much for sharing with us your awesome tool.

I have an issue using kubens for changing my namespace

Demo : 

```bash
INFO: k8s-vault session started

❯ kubens myns
error: open /home/myuser/.kube/k8s-vault-kubeconfig-1101772.yaml: permission denied
❯ ll /home/myuser/.kube/k8s-vault-kubeconfig-1101772.yaml
.r-------- myuser myuser 974 B Wed Dec  7 13:59:08 2022  /home/myuser/.kube/k8s-vault-kubeconfig-1101772.yaml
```

**Comment by anapsix** [comment]
I suspect kubens wants to update the default context in the YAML k8s-vault generated..

**Comment by anapsix** [comment]
give the [v0.4.3](https://github.com/anapsix/k8s-vault.cr/releases/tag/v0.4.3) a try

**Comment by amezioud** [comment]
Fixed quickly. Thanks a lot. I'll try the new release tomorrow indeed !

**Comment by amezioud** [comment]
I confirm, It's working right now.

```bash
INFO: k8s-vault session started
❯ kbx myns
Switched to context "myns".
```
